version: '3.4'

networks:
  orders:
    name: orders-network
    
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - orders